// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/quantex.proto

package GrpcQuantex

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	order "github.com/zsmartex/pkg/Grpc/order"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UpdateOrderRequest struct {
	Order                *order.Order `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UpdateOrderRequest) Reset()         { *m = UpdateOrderRequest{} }
func (m *UpdateOrderRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateOrderRequest) ProtoMessage()    {}
func (*UpdateOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_28987a97d15235d8, []int{0}
}

func (m *UpdateOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateOrderRequest.Unmarshal(m, b)
}
func (m *UpdateOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateOrderRequest.Marshal(b, m, deterministic)
}
func (m *UpdateOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateOrderRequest.Merge(m, src)
}
func (m *UpdateOrderRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateOrderRequest.Size(m)
}
func (m *UpdateOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateOrderRequest proto.InternalMessageInfo

func (m *UpdateOrderRequest) GetOrder() *order.Order {
	if m != nil {
		return m.Order
	}
	return nil
}

type ReloadStrategyRequest struct {
	StrategyId           int64    `protobuf:"varint,1,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReloadStrategyRequest) Reset()         { *m = ReloadStrategyRequest{} }
func (m *ReloadStrategyRequest) String() string { return proto.CompactTextString(m) }
func (*ReloadStrategyRequest) ProtoMessage()    {}
func (*ReloadStrategyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_28987a97d15235d8, []int{1}
}

func (m *ReloadStrategyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReloadStrategyRequest.Unmarshal(m, b)
}
func (m *ReloadStrategyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReloadStrategyRequest.Marshal(b, m, deterministic)
}
func (m *ReloadStrategyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReloadStrategyRequest.Merge(m, src)
}
func (m *ReloadStrategyRequest) XXX_Size() int {
	return xxx_messageInfo_ReloadStrategyRequest.Size(m)
}
func (m *ReloadStrategyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReloadStrategyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReloadStrategyRequest proto.InternalMessageInfo

func (m *ReloadStrategyRequest) GetStrategyId() int64 {
	if m != nil {
		return m.StrategyId
	}
	return 0
}

func init() {
	proto.RegisterType((*UpdateOrderRequest)(nil), "GrpcQuantex.UpdateOrderRequest")
	proto.RegisterType((*ReloadStrategyRequest)(nil), "GrpcQuantex.ReloadStrategyRequest")
}

func init() { proto.RegisterFile("proto/quantex.proto", fileDescriptor_28987a97d15235d8) }

var fileDescriptor_28987a97d15235d8 = []byte{
	// 265 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0x2d, 0xa2, 0x87, 0x14, 0x16, 0x8d, 0x28, 0x52, 0x0f, 0x2b, 0x3d, 0x88, 0xa7, 0x89,
	0xd4, 0x8b, 0xa0, 0x27, 0x41, 0xd4, 0x8b, 0x62, 0x17, 0x2f, 0x5e, 0x24, 0x6d, 0xc6, 0x58, 0xdc,
	0x9a, 0x6c, 0x3a, 0x95, 0x5d, 0x7f, 0x92, 0xbf, 0x52, 0x9a, 0x6c, 0xa1, 0x8b, 0xee, 0x31, 0x6f,
	0x5e, 0xbe, 0x79, 0x8f, 0x61, 0x7b, 0xd6, 0x19, 0x32, 0x62, 0xd6, 0xca, 0x4f, 0xc2, 0x39, 0xf8,
	0x17, 0x8f, 0x6f, 0x9d, 0x2d, 0x9f, 0x82, 0x94, 0x1c, 0x69, 0x63, 0xf4, 0x14, 0x85, 0x1f, 0x15,
	0xed, 0x9b, 0xc0, 0xda, 0xd2, 0x22, 0x38, 0x93, 0xdd, 0xf0, 0xdd, 0x38, 0x85, 0x2e, 0x48, 0xe9,
	0x15, 0xe3, 0xcf, 0x56, 0x49, 0xc2, 0xc7, 0x4e, 0xcc, 0x71, 0xd6, 0x62, 0x43, 0xfc, 0x84, 0x6d,
	0x79, 0xd3, 0x61, 0x74, 0x1c, 0x9d, 0xc6, 0xd9, 0x0e, 0x74, 0x2b, 0xbc, 0x03, 0x82, 0x2f, 0x8c,
	0xd3, 0x0b, 0xb6, 0x9f, 0xe3, 0xd4, 0x48, 0x35, 0x21, 0x27, 0x09, 0xf5, 0xa2, 0x07, 0x8c, 0x59,
	0xdc, 0x2c, 0xa5, 0xd7, 0x4a, 0x79, 0xcc, 0x66, 0xce, 0x7a, 0xe9, 0x5e, 0x65, 0x3f, 0x11, 0x1b,
	0x2d, 0x33, 0x4f, 0xd0, 0x7d, 0x55, 0x25, 0xf2, 0x3b, 0x16, 0x0f, 0xa2, 0xf0, 0x31, 0x0c, 0x7a,
	0xc1, 0xdf, 0x90, 0xc9, 0x01, 0x84, 0xae, 0xd0, 0x77, 0x85, 0x9b, 0xae, 0x6b, 0xba, 0xc1, 0x1f,
	0xd8, 0x68, 0x35, 0x16, 0x4f, 0x57, 0x60, 0xff, 0x66, 0x5e, 0xcf, 0xbb, 0xce, 0x5e, 0xce, 0x74,
	0x45, 0xef, 0x6d, 0x01, 0xa5, 0xa9, 0xc5, 0x77, 0x53, 0x4b, 0x47, 0x38, 0x17, 0xf6, 0x43, 0x8b,
	0x0e, 0xdb, 0xdf, 0xe3, 0x72, 0xb0, 0xa3, 0xd8, 0xf6, 0x94, 0xf3, 0xdf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x9f, 0x07, 0x60, 0x75, 0xb3, 0x01, 0x00, 0x00,
}
