// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/symbol.proto

package GrpcSymbol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Symbol struct {
	BaseCurrency         string   `protobuf:"bytes,1,opt,name=base_currency,json=baseCurrency,proto3" json:"base_currency,omitempty"`
	QuoteCurrency        string   `protobuf:"bytes,2,opt,name=quote_currency,json=quoteCurrency,proto3" json:"quote_currency,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Symbol) Reset()         { *m = Symbol{} }
func (m *Symbol) String() string { return proto.CompactTextString(m) }
func (*Symbol) ProtoMessage()    {}
func (*Symbol) Descriptor() ([]byte, []int) {
	return fileDescriptor_ede4269c7a4cbaa8, []int{0}
}

func (m *Symbol) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Symbol.Unmarshal(m, b)
}
func (m *Symbol) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Symbol.Marshal(b, m, deterministic)
}
func (m *Symbol) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Symbol.Merge(m, src)
}
func (m *Symbol) XXX_Size() int {
	return xxx_messageInfo_Symbol.Size(m)
}
func (m *Symbol) XXX_DiscardUnknown() {
	xxx_messageInfo_Symbol.DiscardUnknown(m)
}

var xxx_messageInfo_Symbol proto.InternalMessageInfo

func (m *Symbol) GetBaseCurrency() string {
	if m != nil {
		return m.BaseCurrency
	}
	return ""
}

func (m *Symbol) GetQuoteCurrency() string {
	if m != nil {
		return m.QuoteCurrency
	}
	return ""
}

func init() {
	proto.RegisterType((*Symbol)(nil), "GrpcSymbol.Symbol")
}

func init() { proto.RegisterFile("proto/symbol.proto", fileDescriptor_ede4269c7a4cbaa8) }

var fileDescriptor_ede4269c7a4cbaa8 = []byte{
	// 144 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0xae, 0xcc, 0x4d, 0xca, 0xcf, 0xd1, 0x03, 0x73, 0x84, 0xb8, 0xdc, 0x8b, 0x0a,
	0x92, 0x83, 0xc1, 0x22, 0x4a, 0x21, 0x5c, 0x6c, 0x10, 0x96, 0x90, 0x32, 0x17, 0x6f, 0x52, 0x62,
	0x71, 0x6a, 0x7c, 0x72, 0x69, 0x51, 0x51, 0x6a, 0x5e, 0x72, 0xa5, 0x04, 0xa3, 0x02, 0xa3, 0x06,
	0x67, 0x10, 0x0f, 0x48, 0xd0, 0x19, 0x2a, 0x26, 0xa4, 0xca, 0xc5, 0x57, 0x58, 0x9a, 0x5f, 0x82,
	0xa4, 0x8a, 0x09, 0xac, 0x8a, 0x17, 0x2c, 0x0a, 0x53, 0xe6, 0x64, 0x10, 0xa5, 0x97, 0x9e, 0x59,
	0x92, 0x51, 0x9a, 0xa4, 0x97, 0x9c, 0x9f, 0xab, 0x5f, 0x55, 0x9c, 0x9b, 0x58, 0x54, 0x92, 0x5a,
	0xa1, 0x5f, 0x90, 0x9d, 0xae, 0x0f, 0xb2, 0x1b, 0xea, 0x1c, 0x6b, 0x84, 0x3b, 0x92, 0xd8, 0xc0,
	0x4e, 0x33, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xb2, 0x87, 0x7c, 0xbe, 0xb0, 0x00, 0x00, 0x00,
}
