// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/engine/engine.proto

package GrpcEngine

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Decimal struct {
	Val                  int64    `protobuf:"varint,1,opt,name=Val,proto3" json:"Val,omitempty"`
	Exp                  int32    `protobuf:"varint,2,opt,name=Exp,proto3" json:"Exp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Decimal) Reset()         { *m = Decimal{} }
func (m *Decimal) String() string { return proto.CompactTextString(m) }
func (*Decimal) ProtoMessage()    {}
func (*Decimal) Descriptor() ([]byte, []int) {
	return fileDescriptor_92049aa8475a6275, []int{0}
}

func (m *Decimal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Decimal.Unmarshal(m, b)
}
func (m *Decimal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Decimal.Marshal(b, m, deterministic)
}
func (m *Decimal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Decimal.Merge(m, src)
}
func (m *Decimal) XXX_Size() int {
	return xxx_messageInfo_Decimal.Size(m)
}
func (m *Decimal) XXX_DiscardUnknown() {
	xxx_messageInfo_Decimal.DiscardUnknown(m)
}

var xxx_messageInfo_Decimal proto.InternalMessageInfo

func (m *Decimal) GetVal() int64 {
	if m != nil {
		return m.Val
	}
	return 0
}

func (m *Decimal) GetExp() int32 {
	if m != nil {
		return m.Exp
	}
	return 0
}

type BookOrder struct {
	PriceQuantity        []*Decimal `protobuf:"bytes,1,rep,name=price_quantity,json=priceQuantity,proto3" json:"price_quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *BookOrder) Reset()         { *m = BookOrder{} }
func (m *BookOrder) String() string { return proto.CompactTextString(m) }
func (*BookOrder) ProtoMessage()    {}
func (*BookOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_92049aa8475a6275, []int{1}
}

func (m *BookOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookOrder.Unmarshal(m, b)
}
func (m *BookOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookOrder.Marshal(b, m, deterministic)
}
func (m *BookOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookOrder.Merge(m, src)
}
func (m *BookOrder) XXX_Size() int {
	return xxx_messageInfo_BookOrder.Size(m)
}
func (m *BookOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_BookOrder.DiscardUnknown(m)
}

var xxx_messageInfo_BookOrder proto.InternalMessageInfo

func (m *BookOrder) GetPriceQuantity() []*Decimal {
	if m != nil {
		return m.PriceQuantity
	}
	return nil
}

type FetchOrderBookRequest struct {
	Market               string   `protobuf:"bytes,1,opt,name=market,proto3" json:"market,omitempty"`
	Limit                int64    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchOrderBookRequest) Reset()         { *m = FetchOrderBookRequest{} }
func (m *FetchOrderBookRequest) String() string { return proto.CompactTextString(m) }
func (*FetchOrderBookRequest) ProtoMessage()    {}
func (*FetchOrderBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_92049aa8475a6275, []int{2}
}

func (m *FetchOrderBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchOrderBookRequest.Unmarshal(m, b)
}
func (m *FetchOrderBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchOrderBookRequest.Marshal(b, m, deterministic)
}
func (m *FetchOrderBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchOrderBookRequest.Merge(m, src)
}
func (m *FetchOrderBookRequest) XXX_Size() int {
	return xxx_messageInfo_FetchOrderBookRequest.Size(m)
}
func (m *FetchOrderBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchOrderBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FetchOrderBookRequest proto.InternalMessageInfo

func (m *FetchOrderBookRequest) GetMarket() string {
	if m != nil {
		return m.Market
	}
	return ""
}

func (m *FetchOrderBookRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type FetchOrderBookResponse struct {
	Market               string       `protobuf:"bytes,1,opt,name=market,proto3" json:"market,omitempty"`
	Bids                 []*BookOrder `protobuf:"bytes,2,rep,name=Bids,proto3" json:"Bids,omitempty"`
	Asks                 []*BookOrder `protobuf:"bytes,3,rep,name=Asks,proto3" json:"Asks,omitempty"`
	Sequence             int64        `protobuf:"varint,4,opt,name=sequence,proto3" json:"sequence,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *FetchOrderBookResponse) Reset()         { *m = FetchOrderBookResponse{} }
func (m *FetchOrderBookResponse) String() string { return proto.CompactTextString(m) }
func (*FetchOrderBookResponse) ProtoMessage()    {}
func (*FetchOrderBookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_92049aa8475a6275, []int{3}
}

func (m *FetchOrderBookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchOrderBookResponse.Unmarshal(m, b)
}
func (m *FetchOrderBookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchOrderBookResponse.Marshal(b, m, deterministic)
}
func (m *FetchOrderBookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchOrderBookResponse.Merge(m, src)
}
func (m *FetchOrderBookResponse) XXX_Size() int {
	return xxx_messageInfo_FetchOrderBookResponse.Size(m)
}
func (m *FetchOrderBookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchOrderBookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FetchOrderBookResponse proto.InternalMessageInfo

func (m *FetchOrderBookResponse) GetMarket() string {
	if m != nil {
		return m.Market
	}
	return ""
}

func (m *FetchOrderBookResponse) GetBids() []*BookOrder {
	if m != nil {
		return m.Bids
	}
	return nil
}

func (m *FetchOrderBookResponse) GetAsks() []*BookOrder {
	if m != nil {
		return m.Asks
	}
	return nil
}

func (m *FetchOrderBookResponse) GetSequence() int64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

type CalcMarketOrderRequest struct {
	Market               string   `protobuf:"bytes,1,opt,name=market,proto3" json:"market,omitempty"`
	Side                 string   `protobuf:"bytes,2,opt,name=side,proto3" json:"side,omitempty"`
	Quantity             *Decimal `protobuf:"bytes,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Volume               *Decimal `protobuf:"bytes,4,opt,name=volume,proto3" json:"volume,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CalcMarketOrderRequest) Reset()         { *m = CalcMarketOrderRequest{} }
func (m *CalcMarketOrderRequest) String() string { return proto.CompactTextString(m) }
func (*CalcMarketOrderRequest) ProtoMessage()    {}
func (*CalcMarketOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_92049aa8475a6275, []int{4}
}

func (m *CalcMarketOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalcMarketOrderRequest.Unmarshal(m, b)
}
func (m *CalcMarketOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalcMarketOrderRequest.Marshal(b, m, deterministic)
}
func (m *CalcMarketOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalcMarketOrderRequest.Merge(m, src)
}
func (m *CalcMarketOrderRequest) XXX_Size() int {
	return xxx_messageInfo_CalcMarketOrderRequest.Size(m)
}
func (m *CalcMarketOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CalcMarketOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CalcMarketOrderRequest proto.InternalMessageInfo

func (m *CalcMarketOrderRequest) GetMarket() string {
	if m != nil {
		return m.Market
	}
	return ""
}

func (m *CalcMarketOrderRequest) GetSide() string {
	if m != nil {
		return m.Side
	}
	return ""
}

func (m *CalcMarketOrderRequest) GetQuantity() *Decimal {
	if m != nil {
		return m.Quantity
	}
	return nil
}

func (m *CalcMarketOrderRequest) GetVolume() *Decimal {
	if m != nil {
		return m.Volume
	}
	return nil
}

type CalcMarketOrderResponse struct {
	Quantity             *Decimal `protobuf:"bytes,1,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Locked               *Decimal `protobuf:"bytes,2,opt,name=locked,proto3" json:"locked,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CalcMarketOrderResponse) Reset()         { *m = CalcMarketOrderResponse{} }
func (m *CalcMarketOrderResponse) String() string { return proto.CompactTextString(m) }
func (*CalcMarketOrderResponse) ProtoMessage()    {}
func (*CalcMarketOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_92049aa8475a6275, []int{5}
}

func (m *CalcMarketOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalcMarketOrderResponse.Unmarshal(m, b)
}
func (m *CalcMarketOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalcMarketOrderResponse.Marshal(b, m, deterministic)
}
func (m *CalcMarketOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalcMarketOrderResponse.Merge(m, src)
}
func (m *CalcMarketOrderResponse) XXX_Size() int {
	return xxx_messageInfo_CalcMarketOrderResponse.Size(m)
}
func (m *CalcMarketOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CalcMarketOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CalcMarketOrderResponse proto.InternalMessageInfo

func (m *CalcMarketOrderResponse) GetQuantity() *Decimal {
	if m != nil {
		return m.Quantity
	}
	return nil
}

func (m *CalcMarketOrderResponse) GetLocked() *Decimal {
	if m != nil {
		return m.Locked
	}
	return nil
}

type FetchMarketPriceRequest struct {
	Market               string   `protobuf:"bytes,1,opt,name=market,proto3" json:"market,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchMarketPriceRequest) Reset()         { *m = FetchMarketPriceRequest{} }
func (m *FetchMarketPriceRequest) String() string { return proto.CompactTextString(m) }
func (*FetchMarketPriceRequest) ProtoMessage()    {}
func (*FetchMarketPriceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_92049aa8475a6275, []int{6}
}

func (m *FetchMarketPriceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchMarketPriceRequest.Unmarshal(m, b)
}
func (m *FetchMarketPriceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchMarketPriceRequest.Marshal(b, m, deterministic)
}
func (m *FetchMarketPriceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchMarketPriceRequest.Merge(m, src)
}
func (m *FetchMarketPriceRequest) XXX_Size() int {
	return xxx_messageInfo_FetchMarketPriceRequest.Size(m)
}
func (m *FetchMarketPriceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchMarketPriceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FetchMarketPriceRequest proto.InternalMessageInfo

func (m *FetchMarketPriceRequest) GetMarket() string {
	if m != nil {
		return m.Market
	}
	return ""
}

type FetchMarketPriceResponse struct {
	Price                *Decimal `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchMarketPriceResponse) Reset()         { *m = FetchMarketPriceResponse{} }
func (m *FetchMarketPriceResponse) String() string { return proto.CompactTextString(m) }
func (*FetchMarketPriceResponse) ProtoMessage()    {}
func (*FetchMarketPriceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_92049aa8475a6275, []int{7}
}

func (m *FetchMarketPriceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchMarketPriceResponse.Unmarshal(m, b)
}
func (m *FetchMarketPriceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchMarketPriceResponse.Marshal(b, m, deterministic)
}
func (m *FetchMarketPriceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchMarketPriceResponse.Merge(m, src)
}
func (m *FetchMarketPriceResponse) XXX_Size() int {
	return xxx_messageInfo_FetchMarketPriceResponse.Size(m)
}
func (m *FetchMarketPriceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchMarketPriceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FetchMarketPriceResponse proto.InternalMessageInfo

func (m *FetchMarketPriceResponse) GetPrice() *Decimal {
	if m != nil {
		return m.Price
	}
	return nil
}

func init() {
	proto.RegisterType((*Decimal)(nil), "service.Decimal")
	proto.RegisterType((*BookOrder)(nil), "service.BookOrder")
	proto.RegisterType((*FetchOrderBookRequest)(nil), "service.FetchOrderBookRequest")
	proto.RegisterType((*FetchOrderBookResponse)(nil), "service.FetchOrderBookResponse")
	proto.RegisterType((*CalcMarketOrderRequest)(nil), "service.CalcMarketOrderRequest")
	proto.RegisterType((*CalcMarketOrderResponse)(nil), "service.CalcMarketOrderResponse")
	proto.RegisterType((*FetchMarketPriceRequest)(nil), "service.FetchMarketPriceRequest")
	proto.RegisterType((*FetchMarketPriceResponse)(nil), "service.FetchMarketPriceResponse")
}

func init() { proto.RegisterFile("proto/engine/engine.proto", fileDescriptor_92049aa8475a6275) }

var fileDescriptor_92049aa8475a6275 = []byte{
	// 453 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xcf, 0x6f, 0xd3, 0x30,
	0x14, 0x26, 0x4d, 0xdb, 0xad, 0x0f, 0x31, 0x2a, 0x8b, 0x6d, 0xa1, 0x42, 0x23, 0xf8, 0x30, 0xe5,
	0x00, 0x45, 0x8c, 0x03, 0x07, 0x4e, 0x84, 0x15, 0x4e, 0x13, 0xe0, 0x49, 0x93, 0xe0, 0x82, 0x82,
	0x63, 0x6d, 0x56, 0x7e, 0x36, 0x76, 0x27, 0xf8, 0x5f, 0x90, 0xf8, 0x57, 0x91, 0x9f, 0x4d, 0x60,
	0x6d, 0x42, 0x77, 0xea, 0xb3, 0xbf, 0xcf, 0xdf, 0xfb, 0xfc, 0xf5, 0xc5, 0xf0, 0xb0, 0x6e, 0x2a,
	0x5d, 0x3d, 0x17, 0xe5, 0xa5, 0x2c, 0x85, 0xfb, 0x99, 0xe3, 0x1e, 0xd9, 0x51, 0xa2, 0xb9, 0x96,
	0x5c, 0xd0, 0x67, 0xb0, 0x73, 0x2a, 0xb8, 0x2c, 0x92, 0x9c, 0x4c, 0xc1, 0xbf, 0x48, 0xf2, 0xc0,
	0x0b, 0xbd, 0xc8, 0x67, 0xa6, 0x34, 0x3b, 0x8b, 0xef, 0x75, 0x30, 0x08, 0xbd, 0x68, 0xc4, 0x4c,
	0x49, 0x4f, 0x61, 0x12, 0x57, 0x55, 0xf6, 0xa1, 0x49, 0x45, 0x43, 0x5e, 0xc1, 0x5e, 0xdd, 0x48,
	0x2e, 0xbe, 0x2e, 0x57, 0x49, 0xa9, 0xa5, 0xfe, 0x11, 0x78, 0xa1, 0x1f, 0xdd, 0x3d, 0x99, 0xce,
	0x9d, 0xfa, 0xdc, 0x49, 0xb3, 0x7b, 0xc8, 0xfb, 0xe4, 0x68, 0x74, 0x01, 0xfb, 0xef, 0x84, 0xe6,
	0x57, 0x28, 0x63, 0xf4, 0x98, 0x58, 0xae, 0x84, 0xd2, 0xe4, 0x00, 0xc6, 0x45, 0xd2, 0x64, 0x42,
	0xa3, 0x8b, 0x09, 0x73, 0x2b, 0xf2, 0x00, 0x46, 0xb9, 0x2c, 0xa4, 0x46, 0x2b, 0x3e, 0xb3, 0x0b,
	0xfa, 0xd3, 0x83, 0x83, 0x75, 0x1d, 0x55, 0x57, 0xa5, 0x12, 0xbd, 0x42, 0xc7, 0x30, 0x8c, 0x65,
	0xaa, 0x82, 0x01, 0x1a, 0x25, 0xad, 0xd1, 0xf6, 0x52, 0x0c, 0x71, 0xc3, 0x7b, 0xa3, 0x32, 0x15,
	0xf8, 0xfd, 0x3c, 0x83, 0x93, 0x19, 0xec, 0x2a, 0xe3, 0xbd, 0xe4, 0x22, 0x18, 0xa2, 0xb7, 0x76,
	0x8d, 0xf6, 0xde, 0x26, 0x39, 0x3f, 0xc3, 0xd6, 0xf6, 0xd4, 0x96, 0x7b, 0x12, 0x18, 0x2a, 0x99,
	0x0a, 0xbc, 0xe6, 0x84, 0x61, 0x4d, 0x9e, 0xc2, 0x6e, 0x9b, 0xaf, 0x1f, 0x7a, 0x9d, 0xf9, 0xb6,
	0x0c, 0x12, 0xc1, 0xf8, 0xba, 0xca, 0x57, 0x85, 0xb5, 0xd3, 0xc5, 0x75, 0x38, 0x5d, 0xc2, 0xe1,
	0x86, 0x3b, 0x97, 0xde, 0xbf, 0x2d, 0xbd, 0xdb, 0xb4, 0xcc, 0x2b, 0x9e, 0x89, 0x14, 0x6d, 0x77,
	0xb6, 0xb4, 0x38, 0x7d, 0x01, 0x87, 0xf8, 0x7f, 0xd9, 0x9e, 0x1f, 0xcd, 0x4c, 0x6c, 0x49, 0x84,
	0xc6, 0x10, 0x6c, 0x1e, 0x71, 0x36, 0x8f, 0x61, 0x84, 0x73, 0xd5, 0xeb, 0xd1, 0xc2, 0x27, 0xbf,
	0x06, 0xb0, 0x7f, 0x96, 0x68, 0x7e, 0x25, 0xcb, 0xcb, 0x05, 0x7e, 0x05, 0xe7, 0x96, 0x48, 0xce,
	0x61, 0xef, 0xe6, 0x00, 0x91, 0xa3, 0x56, 0xa4, 0x73, 0x42, 0x67, 0x8f, 0x7b, 0x71, 0x6b, 0x8a,
	0xde, 0x21, 0x17, 0x70, 0x7f, 0x2d, 0x58, 0xf2, 0xf7, 0x54, 0xf7, 0x40, 0xcc, 0xc2, 0x7e, 0x42,
	0xab, 0xfb, 0x19, 0xa6, 0xeb, 0x51, 0x90, 0xf0, 0xa6, 0x9d, 0xcd, 0x60, 0x67, 0x4f, 0xfe, 0xc3,
	0xf8, 0x23, 0x1d, 0x1f, 0x7d, 0x79, 0x64, 0xdf, 0x8a, 0xf7, 0x4d, 0xcd, 0xdd, 0x4b, 0xf1, 0xda,
	0xd4, 0x36, 0xae, 0x6f, 0x63, 0x44, 0x5f, 0xfe, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xd7, 0xd0, 0xd3,
	0xff, 0x52, 0x04, 0x00, 0x00,
}
