// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/engine.proto

package GrpcEngine

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	order "github.com/zsmartex/pkg/Grpc/order"
	symbol "github.com/zsmartex/pkg/Grpc/symbol"
	utils "github.com/zsmartex/pkg/Grpc/utils"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FetchOrderRequest struct {
	OrderKey             *order.OrderKey `protobuf:"bytes,1,opt,name=order_key,json=orderKey,proto3" json:"order_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *FetchOrderRequest) Reset()         { *m = FetchOrderRequest{} }
func (m *FetchOrderRequest) String() string { return proto.CompactTextString(m) }
func (*FetchOrderRequest) ProtoMessage()    {}
func (*FetchOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfae4ba294cbbcbf, []int{0}
}

func (m *FetchOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchOrderRequest.Unmarshal(m, b)
}
func (m *FetchOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchOrderRequest.Marshal(b, m, deterministic)
}
func (m *FetchOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchOrderRequest.Merge(m, src)
}
func (m *FetchOrderRequest) XXX_Size() int {
	return xxx_messageInfo_FetchOrderRequest.Size(m)
}
func (m *FetchOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FetchOrderRequest proto.InternalMessageInfo

func (m *FetchOrderRequest) GetOrderKey() *order.OrderKey {
	if m != nil {
		return m.OrderKey
	}
	return nil
}

type FetchOrderResponse struct {
	Order                *order.Order `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *FetchOrderResponse) Reset()         { *m = FetchOrderResponse{} }
func (m *FetchOrderResponse) String() string { return proto.CompactTextString(m) }
func (*FetchOrderResponse) ProtoMessage()    {}
func (*FetchOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfae4ba294cbbcbf, []int{1}
}

func (m *FetchOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchOrderResponse.Unmarshal(m, b)
}
func (m *FetchOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchOrderResponse.Marshal(b, m, deterministic)
}
func (m *FetchOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchOrderResponse.Merge(m, src)
}
func (m *FetchOrderResponse) XXX_Size() int {
	return xxx_messageInfo_FetchOrderResponse.Size(m)
}
func (m *FetchOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FetchOrderResponse proto.InternalMessageInfo

func (m *FetchOrderResponse) GetOrder() *order.Order {
	if m != nil {
		return m.Order
	}
	return nil
}

type FetchOpenOrdersRequest struct {
	Symbol               *symbol.Symbol `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Side                 string         `protobuf:"bytes,2,opt,name=side,proto3" json:"side,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *FetchOpenOrdersRequest) Reset()         { *m = FetchOpenOrdersRequest{} }
func (m *FetchOpenOrdersRequest) String() string { return proto.CompactTextString(m) }
func (*FetchOpenOrdersRequest) ProtoMessage()    {}
func (*FetchOpenOrdersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfae4ba294cbbcbf, []int{2}
}

func (m *FetchOpenOrdersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchOpenOrdersRequest.Unmarshal(m, b)
}
func (m *FetchOpenOrdersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchOpenOrdersRequest.Marshal(b, m, deterministic)
}
func (m *FetchOpenOrdersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchOpenOrdersRequest.Merge(m, src)
}
func (m *FetchOpenOrdersRequest) XXX_Size() int {
	return xxx_messageInfo_FetchOpenOrdersRequest.Size(m)
}
func (m *FetchOpenOrdersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchOpenOrdersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FetchOpenOrdersRequest proto.InternalMessageInfo

func (m *FetchOpenOrdersRequest) GetSymbol() *symbol.Symbol {
	if m != nil {
		return m.Symbol
	}
	return nil
}

func (m *FetchOpenOrdersRequest) GetSide() string {
	if m != nil {
		return m.Side
	}
	return ""
}

type BookOrder struct {
	PriceQuantity        []*utils.Decimal `protobuf:"bytes,1,rep,name=price_quantity,json=priceQuantity,proto3" json:"price_quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *BookOrder) Reset()         { *m = BookOrder{} }
func (m *BookOrder) String() string { return proto.CompactTextString(m) }
func (*BookOrder) ProtoMessage()    {}
func (*BookOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfae4ba294cbbcbf, []int{3}
}

func (m *BookOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookOrder.Unmarshal(m, b)
}
func (m *BookOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookOrder.Marshal(b, m, deterministic)
}
func (m *BookOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookOrder.Merge(m, src)
}
func (m *BookOrder) XXX_Size() int {
	return xxx_messageInfo_BookOrder.Size(m)
}
func (m *BookOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_BookOrder.DiscardUnknown(m)
}

var xxx_messageInfo_BookOrder proto.InternalMessageInfo

func (m *BookOrder) GetPriceQuantity() []*utils.Decimal {
	if m != nil {
		return m.PriceQuantity
	}
	return nil
}

type FetchOrderBookRequest struct {
	Symbol               *symbol.Symbol `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Limit                int64          `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *FetchOrderBookRequest) Reset()         { *m = FetchOrderBookRequest{} }
func (m *FetchOrderBookRequest) String() string { return proto.CompactTextString(m) }
func (*FetchOrderBookRequest) ProtoMessage()    {}
func (*FetchOrderBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfae4ba294cbbcbf, []int{4}
}

func (m *FetchOrderBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchOrderBookRequest.Unmarshal(m, b)
}
func (m *FetchOrderBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchOrderBookRequest.Marshal(b, m, deterministic)
}
func (m *FetchOrderBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchOrderBookRequest.Merge(m, src)
}
func (m *FetchOrderBookRequest) XXX_Size() int {
	return xxx_messageInfo_FetchOrderBookRequest.Size(m)
}
func (m *FetchOrderBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchOrderBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FetchOrderBookRequest proto.InternalMessageInfo

func (m *FetchOrderBookRequest) GetSymbol() *symbol.Symbol {
	if m != nil {
		return m.Symbol
	}
	return nil
}

func (m *FetchOrderBookRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type FetchOrderBookResponse struct {
	Symbol               *symbol.Symbol `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Bids                 []*BookOrder   `protobuf:"bytes,2,rep,name=Bids,proto3" json:"Bids,omitempty"`
	Asks                 []*BookOrder   `protobuf:"bytes,3,rep,name=Asks,proto3" json:"Asks,omitempty"`
	Sequence             int64          `protobuf:"varint,4,opt,name=sequence,proto3" json:"sequence,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *FetchOrderBookResponse) Reset()         { *m = FetchOrderBookResponse{} }
func (m *FetchOrderBookResponse) String() string { return proto.CompactTextString(m) }
func (*FetchOrderBookResponse) ProtoMessage()    {}
func (*FetchOrderBookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfae4ba294cbbcbf, []int{5}
}

func (m *FetchOrderBookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchOrderBookResponse.Unmarshal(m, b)
}
func (m *FetchOrderBookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchOrderBookResponse.Marshal(b, m, deterministic)
}
func (m *FetchOrderBookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchOrderBookResponse.Merge(m, src)
}
func (m *FetchOrderBookResponse) XXX_Size() int {
	return xxx_messageInfo_FetchOrderBookResponse.Size(m)
}
func (m *FetchOrderBookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchOrderBookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FetchOrderBookResponse proto.InternalMessageInfo

func (m *FetchOrderBookResponse) GetSymbol() *symbol.Symbol {
	if m != nil {
		return m.Symbol
	}
	return nil
}

func (m *FetchOrderBookResponse) GetBids() []*BookOrder {
	if m != nil {
		return m.Bids
	}
	return nil
}

func (m *FetchOrderBookResponse) GetAsks() []*BookOrder {
	if m != nil {
		return m.Asks
	}
	return nil
}

func (m *FetchOrderBookResponse) GetSequence() int64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

type CalcMarketOrderRequest struct {
	Symbol               *symbol.Symbol `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Side                 string         `protobuf:"bytes,2,opt,name=side,proto3" json:"side,omitempty"`
	Quantity             *utils.Decimal `protobuf:"bytes,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Volume               *utils.Decimal `protobuf:"bytes,4,opt,name=volume,proto3" json:"volume,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CalcMarketOrderRequest) Reset()         { *m = CalcMarketOrderRequest{} }
func (m *CalcMarketOrderRequest) String() string { return proto.CompactTextString(m) }
func (*CalcMarketOrderRequest) ProtoMessage()    {}
func (*CalcMarketOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfae4ba294cbbcbf, []int{6}
}

func (m *CalcMarketOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalcMarketOrderRequest.Unmarshal(m, b)
}
func (m *CalcMarketOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalcMarketOrderRequest.Marshal(b, m, deterministic)
}
func (m *CalcMarketOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalcMarketOrderRequest.Merge(m, src)
}
func (m *CalcMarketOrderRequest) XXX_Size() int {
	return xxx_messageInfo_CalcMarketOrderRequest.Size(m)
}
func (m *CalcMarketOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CalcMarketOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CalcMarketOrderRequest proto.InternalMessageInfo

func (m *CalcMarketOrderRequest) GetSymbol() *symbol.Symbol {
	if m != nil {
		return m.Symbol
	}
	return nil
}

func (m *CalcMarketOrderRequest) GetSide() string {
	if m != nil {
		return m.Side
	}
	return ""
}

func (m *CalcMarketOrderRequest) GetQuantity() *utils.Decimal {
	if m != nil {
		return m.Quantity
	}
	return nil
}

func (m *CalcMarketOrderRequest) GetVolume() *utils.Decimal {
	if m != nil {
		return m.Volume
	}
	return nil
}

type CalcMarketOrderResponse struct {
	Quantity             *utils.Decimal `protobuf:"bytes,1,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Locked               *utils.Decimal `protobuf:"bytes,2,opt,name=locked,proto3" json:"locked,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CalcMarketOrderResponse) Reset()         { *m = CalcMarketOrderResponse{} }
func (m *CalcMarketOrderResponse) String() string { return proto.CompactTextString(m) }
func (*CalcMarketOrderResponse) ProtoMessage()    {}
func (*CalcMarketOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfae4ba294cbbcbf, []int{7}
}

func (m *CalcMarketOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalcMarketOrderResponse.Unmarshal(m, b)
}
func (m *CalcMarketOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalcMarketOrderResponse.Marshal(b, m, deterministic)
}
func (m *CalcMarketOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalcMarketOrderResponse.Merge(m, src)
}
func (m *CalcMarketOrderResponse) XXX_Size() int {
	return xxx_messageInfo_CalcMarketOrderResponse.Size(m)
}
func (m *CalcMarketOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CalcMarketOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CalcMarketOrderResponse proto.InternalMessageInfo

func (m *CalcMarketOrderResponse) GetQuantity() *utils.Decimal {
	if m != nil {
		return m.Quantity
	}
	return nil
}

func (m *CalcMarketOrderResponse) GetLocked() *utils.Decimal {
	if m != nil {
		return m.Locked
	}
	return nil
}

type FetchMarketPriceRequest struct {
	Symbol               *symbol.Symbol `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *FetchMarketPriceRequest) Reset()         { *m = FetchMarketPriceRequest{} }
func (m *FetchMarketPriceRequest) String() string { return proto.CompactTextString(m) }
func (*FetchMarketPriceRequest) ProtoMessage()    {}
func (*FetchMarketPriceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfae4ba294cbbcbf, []int{8}
}

func (m *FetchMarketPriceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchMarketPriceRequest.Unmarshal(m, b)
}
func (m *FetchMarketPriceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchMarketPriceRequest.Marshal(b, m, deterministic)
}
func (m *FetchMarketPriceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchMarketPriceRequest.Merge(m, src)
}
func (m *FetchMarketPriceRequest) XXX_Size() int {
	return xxx_messageInfo_FetchMarketPriceRequest.Size(m)
}
func (m *FetchMarketPriceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchMarketPriceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FetchMarketPriceRequest proto.InternalMessageInfo

func (m *FetchMarketPriceRequest) GetSymbol() *symbol.Symbol {
	if m != nil {
		return m.Symbol
	}
	return nil
}

type FetchMarketPriceResponse struct {
	Price                *utils.Decimal `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *FetchMarketPriceResponse) Reset()         { *m = FetchMarketPriceResponse{} }
func (m *FetchMarketPriceResponse) String() string { return proto.CompactTextString(m) }
func (*FetchMarketPriceResponse) ProtoMessage()    {}
func (*FetchMarketPriceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfae4ba294cbbcbf, []int{9}
}

func (m *FetchMarketPriceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchMarketPriceResponse.Unmarshal(m, b)
}
func (m *FetchMarketPriceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchMarketPriceResponse.Marshal(b, m, deterministic)
}
func (m *FetchMarketPriceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchMarketPriceResponse.Merge(m, src)
}
func (m *FetchMarketPriceResponse) XXX_Size() int {
	return xxx_messageInfo_FetchMarketPriceResponse.Size(m)
}
func (m *FetchMarketPriceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchMarketPriceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FetchMarketPriceResponse proto.InternalMessageInfo

func (m *FetchMarketPriceResponse) GetPrice() *utils.Decimal {
	if m != nil {
		return m.Price
	}
	return nil
}

func init() {
	proto.RegisterType((*FetchOrderRequest)(nil), "GrpcEngine.FetchOrderRequest")
	proto.RegisterType((*FetchOrderResponse)(nil), "GrpcEngine.FetchOrderResponse")
	proto.RegisterType((*FetchOpenOrdersRequest)(nil), "GrpcEngine.FetchOpenOrdersRequest")
	proto.RegisterType((*BookOrder)(nil), "GrpcEngine.BookOrder")
	proto.RegisterType((*FetchOrderBookRequest)(nil), "GrpcEngine.FetchOrderBookRequest")
	proto.RegisterType((*FetchOrderBookResponse)(nil), "GrpcEngine.FetchOrderBookResponse")
	proto.RegisterType((*CalcMarketOrderRequest)(nil), "GrpcEngine.CalcMarketOrderRequest")
	proto.RegisterType((*CalcMarketOrderResponse)(nil), "GrpcEngine.CalcMarketOrderResponse")
	proto.RegisterType((*FetchMarketPriceRequest)(nil), "GrpcEngine.FetchMarketPriceRequest")
	proto.RegisterType((*FetchMarketPriceResponse)(nil), "GrpcEngine.FetchMarketPriceResponse")
}

func init() { proto.RegisterFile("proto/engine.proto", fileDescriptor_dfae4ba294cbbcbf) }

var fileDescriptor_dfae4ba294cbbcbf = []byte{
	// 558 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x94, 0x5b, 0x6f, 0xd3, 0x30,
	0x14, 0xc7, 0xc9, 0xda, 0x4e, 0xed, 0x41, 0x8c, 0xcd, 0xd0, 0x2d, 0x8a, 0x04, 0x1a, 0x1e, 0x42,
	0x85, 0x87, 0x74, 0x1a, 0x4f, 0x08, 0x5e, 0x28, 0xeb, 0x78, 0x40, 0x15, 0x90, 0x09, 0x89, 0x21,
	0xa4, 0x2a, 0x4d, 0xad, 0xd6, 0xca, 0xc5, 0x59, 0xec, 0x4c, 0x94, 0x27, 0x3e, 0x14, 0xe2, 0xf3,
	0xa1, 0x1c, 0xbb, 0xe9, 0x75, 0x15, 0x6c, 0x2f, 0x5b, 0x6c, 0xff, 0xfc, 0x3f, 0xff, 0x73, 0xa9,
	0x81, 0xa4, 0x99, 0x50, 0xa2, 0xcd, 0x92, 0x11, 0x4f, 0x98, 0x8b, 0x0b, 0x02, 0xef, 0xb3, 0x34,
	0xe8, 0xe2, 0x8e, 0xb3, 0xa7, 0xcf, 0x73, 0xc5, 0x23, 0xa9, 0x8f, 0xa7, 0x5b, 0x22, 0x1b, 0xb2,
	0xcc, 0x6c, 0x19, 0x15, 0x39, 0x89, 0x07, 0x22, 0xd2, 0x7b, 0xb4, 0x0b, 0x7b, 0x67, 0x4c, 0x05,
	0xe3, 0x8f, 0x05, 0xe7, 0xb1, 0xcb, 0x9c, 0x49, 0x45, 0x8e, 0xa1, 0x81, 0xf7, 0xfa, 0x21, 0x9b,
	0xd8, 0xd6, 0xa1, 0xd5, 0xba, 0x7b, 0xf2, 0xc0, 0x2d, 0xc2, 0x21, 0xe5, 0xe2, 0xdf, 0x0f, 0x6c,
	0xe2, 0xd5, 0x85, 0xf9, 0xa2, 0x6f, 0x80, 0xcc, 0xcb, 0xc8, 0x54, 0x24, 0x92, 0x91, 0x67, 0x50,
	0x43, 0xc2, 0x68, 0xec, 0x2e, 0x6b, 0x78, 0xfa, 0x98, 0x7e, 0x85, 0x7d, 0x7d, 0x3b, 0x65, 0x09,
	0x1e, 0xc8, 0xa9, 0x93, 0x17, 0xb0, 0xad, 0xed, 0x1a, 0x09, 0x82, 0x12, 0xe7, 0x3a, 0x03, 0xfd,
	0xcf, 0x33, 0x04, 0x21, 0x50, 0x95, 0x7c, 0xc8, 0xec, 0xad, 0x43, 0xab, 0xd5, 0xf0, 0xf0, 0x9b,
	0x9e, 0x41, 0xa3, 0x23, 0x44, 0x88, 0xa2, 0xe4, 0x15, 0xec, 0xa4, 0x19, 0x0f, 0x58, 0xff, 0x32,
	0xf7, 0x13, 0xc5, 0x55, 0x91, 0x5b, 0xa5, 0x14, 0xfd, 0x82, 0xc5, 0x3b, 0x65, 0x01, 0x8f, 0xfd,
	0xc8, 0xbb, 0x87, 0xe4, 0x67, 0x03, 0xd2, 0x0b, 0x68, 0xce, 0xf2, 0x2b, 0x14, 0x6f, 0x62, 0xf0,
	0x21, 0xd4, 0x22, 0x1e, 0x73, 0x85, 0x0e, 0x2b, 0x9e, 0x5e, 0xd0, 0x3f, 0xd6, 0x34, 0xfb, 0x99,
	0xb6, 0xa9, 0xdf, 0xff, 0x88, 0x3f, 0x87, 0x6a, 0x87, 0x0f, 0xa5, 0xbd, 0x85, 0x29, 0x35, 0xdd,
	0xd9, 0x74, 0xb8, 0x65, 0x05, 0x3c, 0x44, 0x0a, 0xf4, 0xad, 0x0c, 0xa5, 0x5d, 0xd9, 0x88, 0x16,
	0x08, 0x71, 0xa0, 0x2e, 0x8b, 0x4c, 0x93, 0x80, 0xd9, 0x55, 0x74, 0x5d, 0xae, 0xe9, 0x6f, 0x0b,
	0xf6, 0xdf, 0xf9, 0x51, 0xd0, 0xf3, 0xb3, 0x90, 0xa9, 0x85, 0x01, 0xba, 0x65, 0xdb, 0x88, 0x0b,
	0xf5, 0xb2, 0x47, 0x95, 0x39, 0x85, 0xc5, 0x1e, 0x95, 0x4c, 0x11, 0xef, 0x4a, 0x44, 0x79, 0xac,
	0x4d, 0xae, 0xa7, 0x0d, 0x41, 0x73, 0x38, 0x58, 0x71, 0x6d, 0xea, 0x3d, 0x1f, 0xd6, 0xfa, 0xb7,
	0xb0, 0x91, 0x08, 0x42, 0x36, 0x44, 0xf3, 0xd7, 0x84, 0xd5, 0x04, 0xed, 0xc2, 0x01, 0x76, 0x59,
	0xc7, 0xfd, 0x54, 0x4c, 0xd7, 0x0d, 0xaa, 0x45, 0x4f, 0xc1, 0x5e, 0x95, 0x31, 0xf6, 0x5b, 0x50,
	0xc3, 0xa9, 0xdd, 0xe0, 0x5d, 0x03, 0x27, 0xbf, 0x2a, 0xd0, 0xec, 0xf9, 0x2a, 0x18, 0xf3, 0x64,
	0xa4, 0x3b, 0x7f, 0xce, 0xb2, 0x2b, 0x1e, 0x30, 0xd2, 0x03, 0x98, 0x0d, 0x23, 0x79, 0x34, 0x3f,
	0x1b, 0x2b, 0xef, 0x84, 0xf3, 0xf8, 0xba, 0x63, 0x6d, 0x88, 0xde, 0x21, 0x17, 0xb0, 0xb3, 0x38,
	0xdb, 0xe4, 0xc9, 0xfa, 0x3b, 0x73, 0xbf, 0x29, 0x87, 0x6e, 0x42, 0x4a, 0xe9, 0xef, 0x70, 0x7f,
	0xa9, 0x8f, 0x64, 0xe1, 0xe2, 0xfa, 0xd1, 0x74, 0x8e, 0x36, 0x32, 0xa5, 0x7a, 0x1f, 0x76, 0x97,
	0xeb, 0x4c, 0x8e, 0x56, 0x7c, 0xad, 0x36, 0xd3, 0x79, 0xba, 0x19, 0x9a, 0x06, 0xe8, 0x1c, 0x7f,
	0x73, 0x47, 0x5c, 0x8d, 0xf3, 0x81, 0x1b, 0x88, 0xb8, 0xfd, 0x53, 0xc6, 0x7e, 0xa6, 0xd8, 0x8f,
	0x76, 0x1a, 0x8e, 0xda, 0x85, 0x80, 0x79, 0xeb, 0x5f, 0xcf, 0xc4, 0x06, 0xdb, 0xf8, 0x62, 0xbf,
	0xfc, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x54, 0x83, 0x2b, 0x2d, 0x0d, 0x06, 0x00, 0x00,
}
